version: "3.5"
services:
  db:
    image: postgres:12.4-alpine
    command: 'postgres -c "max_connections=200"'
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_PASSWORD="postgres"
volumes:
  postgres-data:
